### ISSUE TITLE
What are easy ways to tweak the CSS?

### ISSUE THREAD

**Issue by nathanlane** [forestryio/ubuild-jekyll#1]
I love the idea of uBuild, it seems like it opens up so many possibilities. I'm not a front-end developer. Nonetheless, I really couldn't wrap my head around how to tweak the CSS. How does a user do this? Or how even are you all generating the CSS for the current version of uBuild template?

(PS excited by all the front-end tools Forestry.io is churning out)

**Comment by phillipadsmith** [comment]
@nathanlane You can simply add a link to a CSS file like so (in ```_includes/head.html```):

```
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/forestryio/ubuild-blocks@1.0.0/dist/css/ubuild.css"/>
    <link rel="stylesheet" href="my-site-styles.css"/>
```

And then override or tweak as needed.

Hope that helps!

**Comment by cassiewallace** [comment]
Thank you!
