### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by stonksape** [forestryio/ubuild-jekyll#11]
Thanks for open-sourcing this. Any idea how to quickly change the color of the overall theme which is currently a bright yellow?

**Comment by DirtyF** [comment]
You can remove the default call to the external CSS:
https://github.com/forestryio/ubuild-jekyll/blob/master/_includes/head.html#L11

CSS source is here: https://github.com/forestryio/ubuild-blocks/tree/master/src/css

**Comment by ritchieng** [comment]
I'm a newbie, feel free to ignore. But if I don't want to remove the call and just want to edit a file to just change the overall color, which file do I change?

**Comment by stonksape** [comment]
I am a newbie so pardon me. But if i dont want to remove the default call, what file do i change and push to change the color?

**Comment by DirtyF** [comment]
The easiest thing to do here would be for you to download the remote CSS file locally and update the call accordingly for you to be able to change the colors in the CSS.

This demo is meant to serve as an example to demo Forestry blocks, CSS customization is out of the support we can offer.
