### ISSUE TITLE
block-header-1.html's navigation is not responsive

### ISSUE THREAD

**Issue by phillipadsmith** [forestryio/ubuild-jekyll#2]
I'm sure this is a known issue, but the navigation is not (effectively) responsive, e.g.:

<img width="361" alt="homepage_-_ubuild_design_blocks" src="https://user-images.githubusercontent.com/34128/44422287-96684400-a537-11e8-9eb0-feddc004ab0b.png">

Do you have any preferred approaches to this? If so, I can implement and send a PR.

Phillip.

**Comment by phillipadsmith** [comment]
@Germoe Seems that most/many of the blocks that use columns (like the footer with four columns) don't collapse properly at smaller views. Thoughts on how you'd like to see this work?

**Comment by cassiewallace** [comment]
+1

**Comment by DirtyF** [comment]
ubuild is meant as a showcase of Forestry blocks, not a ready to use theme. A pull-request would be of course appreciated if someone wants to fix this. Thanks.
